function [targetPointCloud] = rotatePointCloud(sourcePointCloud, cx, cy, cz, angleOX, angleOY, angleOZ)
% translation by [-cx, -cy, -cz]
tform = rigidtform3d(eye(3,3), [-cx, -cy, -cz]); 
translatedCloud = pctransform(sourcePointCloud, tform);
% rotation by angleOX (in radians)
%tform = rigidtform3d([rad2deg(angleOX),0,0]);
tform = rigidtform3d([ ...
    1, 0, 0; ...
    0,cos(angleOX),-sin(angleOX); ...
    0, sin(angleOX), cos(angleOX) ...
    ], [0, 0, 0]); % OX
rotatedCloud = pctransform(translatedCloud, tform);
% rotation by angleOY (in radians)
%tform = rigidtform3d([0,rad2deg(angleOY),0]);
tform = rigidtform3d([ ...
    cos(angleOY), 0, sin(angleOY); ...
    0,1,0; ...
    -sin(angleOY), 0, cos(angleOY) ...
    ], [0, 0, 0]); % OY
rotatedCloud = pctransform(rotatedCloud, tform);
% rotation by angleOZ (in radians)
%tform = rigidtform3d([0,0,rad2deg(angleOZ)]);
tform = rigidtform3d([ ...
    cos(angleOZ), -sin(angleOZ), 0; ...
    sin(angleOZ),cos(angleOZ),0; ...
    0, 0, 1 ...
    ], [0, 0, 0]); % OZ
rotatedCloud = pctransform(rotatedCloud, tform);
% translation by [cx, cy, cz]
tform = rigidtform3d(eye(3,3), [cx, cy, cz]); 
targetPointCloud = pctransform(rotatedCloud, tform);