% 'useMediaPipe': pass 'true' or 'false' to determine which data to move
function [] = rsMultipleDataBatch(useMediaPipe)
    effectivenessLocationVector = [
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.49", "metric", "manhattan", "location", "I10"), ...
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.49", "metric", "euclidean", "location", "I48"), ...
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.6", "metric", "manhattan", "location", "W10"), ...
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.6", "metric", "euclidean", "location", "W48"), ...
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.49", "metric", "manhattan", "location", "AQ10"), ...
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.49", "metric", "euclidean", "location", "AQ48"), ...
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.6", "metric", "manhattan", "location", "BK10"), ...
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.6", "metric", "euclidean", "location", "BK48"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.49", "metric", "manhattan", "location", "CE10"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.49", "metric", "euclidean", "location", "CE48"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.6", "metric", "manhattan", "location", "CY10"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.6", "metric", "euclidean", "location", "CY48"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.49", "metric", "manhattan", "location", "DS10"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.49", "metric", "euclidean", "location", "DS48"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.6", "metric", "manhattan", "location", "EM10"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.6", "metric", "euclidean", "location", "EM48") ...
    ];
    timeLocationVector = [
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.49", "metric", "manhattan", "location", "S22"), ...
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.49", "metric", "euclidean", "location", "S60"), ...
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.6", "metric", "manhattan", "location", "AG22"), ...
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.6", "metric", "euclidean", "location", "AG60"), ...
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.49", "metric", "manhattan", "location", "BA22"), ...
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.49", "metric", "euclidean", "location", "BA60"), ...
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.6", "metric", "manhattan", "location", "BU22"), ...
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.6", "metric", "euclidean", "location", "BU60"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.49", "metric", "manhattan", "location", "CO22"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.49", "metric", "euclidean", "location", "CO60"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.6", "metric", "manhattan", "location", "DI22"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.6", "metric", "euclidean", "location", "DI60"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.49", "metric", "manhattan", "location", "EC22"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.49", "metric", "euclidean", "location", "EC60"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.6", "metric", "manhattan", "location", "EW22"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.6", "metric", "euclidean", "location", "EW60") ...
    ];
    % Save effectivenesses
    for e=effectivenessLocationVector
        readAndSaveDataBatch(e.minNeighborsFraction, e.selfAdjustmentWeight, e.socialAdjustmentWeight, e.metric, true, e.location, useMediaPipe);
    end
    % Save times
    for t=timeLocationVector
        readAndSaveDataBatch(t.minNeighborsFraction, t.selfAdjustmentWeight, t.socialAdjustmentWeight, t.metric, false, t.location, useMediaPipe);
    end
    disp("All saved!");