% 'useMediaPipe': pass 'true' or 'false' to determine which data to move
function [] = rsMultipleDataBatch(useMediaPipe)
    effectivenessLocationVector = [
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.49", "metric", "manhattan", "location", "C10"), ...
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.49", "metric", "euclidean", "location", "C39"), ...
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.6", "metric", "manhattan", "location", "S10"), ...
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.6", "metric", "euclidean", "location", "S39"), ...
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.49", "metric", "manhattan", "location", "AI10"), ...
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.49", "metric", "euclidean", "location", "AI39"), ...
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.6", "metric", "manhattan", "location", "AY10"), ...
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.6", "metric", "euclidean", "location", "AY39"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.49", "metric", "manhattan", "location", "BO10"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.49", "metric", "euclidean", "location", "BO39"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.6", "metric", "manhattan", "location", "CE10"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.6", "metric", "euclidean", "location", "CE39"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.49", "metric", "manhattan", "location", "CU10"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.49", "metric", "euclidean", "location", "CU39"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.6", "metric", "manhattan", "location", "DK10"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.6", "metric", "euclidean", "location", "DK39") ...
    ];
    timeLocationVector = [
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.49", "metric", "manhattan", "location", "K19"), ...
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.49", "metric", "euclidean", "location", "K48"), ...
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.6", "metric", "manhattan", "location", "AA19"), ...
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.6", "metric", "euclidean", "location", "AA48"), ...
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.49", "metric", "manhattan", "location", "AQ19"), ...
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.49", "metric", "euclidean", "location", "AQ48"), ...
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.6", "metric", "manhattan", "location", "BG19"), ...
        struct("minNeighborsFraction", "0.25", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.6", "metric", "euclidean", "location", "BG48"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.49", "metric", "manhattan", "location", "BW19"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.49", "metric", "euclidean", "location", "BW48"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.6", "metric", "manhattan", "location", "CM19"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.49", "socialAdjustmentWeight", "1.6", "metric", "euclidean", "location", "CM48"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.49", "metric", "manhattan", "location", "DC19"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.49", "metric", "euclidean", "location", "DC48"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.6", "metric", "manhattan", "location", "DS19"), ...
        struct("minNeighborsFraction", "0.4", "selfAdjustmentWeight", "1.6", "socialAdjustmentWeight", "1.6", "metric", "euclidean", "location", "DS48") ...
    ];
    % Save effectivenesses
    for e=effectivenessLocationVector
        readAndSaveDataBatch(e.minNeighborsFraction, e.selfAdjustmentWeight, e.socialAdjustmentWeight, e.metric, true, e.location, useMediaPipe);
    end
    % Save times
    for t=timeLocationVector
        readAndSaveDataBatch(t.minNeighborsFraction, t.selfAdjustmentWeight, t.socialAdjustmentWeight, t.metric, false, t.location, useMediaPipe);
    end
    disp("All saved!");